version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    working_directory: ~/fin-web
    steps:
      - checkout
      - node/install:
          npm-version: latest
          node-version: 12.18.1
      - run:
          command: npm ci
      - run: npm install
      - run: npm test
      - run: CI=false npm run build
      - save_cache:
          key: build1
          paths:
            - build
            - ./build

  deploy:
    machine:
      enabled: true
    working_directory: ~/fin-web
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d9:05:3e:62:c8:e6:04:32:84:39:f5:30:38:a3:3c:d3"
      - restore_cache:
          key: build1
      - run:
          name: Deploy over ssh
          command: |
            scp -r ~/fin-web/build/* "$SSH_USER@$SSH_HOST:/var/www/html/fin-web"          

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
